using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace Presentacion.Formularios.Ventas
{
    public partial class xfrm_consulta_inventario:DevExpress.XtraEditors.XtraForm
    {
        public xfrm_consulta_inventario( )
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // var Recurso= Negocio.ClasesCN.InventarioCN.Kardex_SelectVenta();
            pivot_Kardex_consulta.DataSource = new System.ComponentModel.BindingList<Entidades.Kardex_SELECT_Result>();
            if (Clases.UsuarioLogueado.vID_Empleado == 2)
                pivot_Kardex_consulta.DataSource = Negocio.ClasesCN.InventarioCN.Kardex_Select().Where(o => o.id_bodega == 4);
            else
                pivot_Kardex_consulta.DataSource = Negocio.ClasesCN.InventarioCN.Kardex_Select();

        }

        private void xfrm_consulta_inventario_Load(object sender,EventArgs e)
        {
            //binding_Kardex.DataSource = Negocio.ClasesCN.InventarioCN.Kardex_SelectVenta();
            //pivot_Kardex_consulta.DataSource = binding_Kardex;
        }
    }
}