//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonos_Caja
    {
        public int id { get; set; }
        public int id_documento { get; set; }
        public int id_cliente { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fecha { get; set; }
        public string observacion { get; set; }
        public int estado { get; set; }
        public bool activo { get; set; }
        public int id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
