//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionDocumentos
    {
        public int id_aplicacion { get; set; }
        public Nullable<int> id_documento_aplicado { get; set; }
        public Nullable<int> id_documento_a_aplicar { get; set; }
        public Nullable<System.DateTime> fecha_aplicacion { get; set; }
        public Nullable<decimal> saldo_pendiente { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<decimal> monto_aplicado { get; set; }
    
        public virtual DocumentosCuentasCobrar DocumentosCuentasCobrar { get; set; }
        public virtual DocumentosCuentasCobrar DocumentosCuentasCobrar1 { get; set; }
    }
}
