//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arqueos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arqueos()
        {
            this.Arqueo_detalle = new HashSet<Arqueo_detalle>();
        }
    
        public int id_registro { get; set; }
        public Nullable<System.DateTime> fecha_arqueo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_empleado_registro { get; set; }
        public Nullable<int> estado_arqueo { get; set; }
        public Nullable<int> numero_arqueo { get; set; }
        public Nullable<decimal> tipo_camibio { get; set; }
        public Nullable<int> tipo_arqueo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arqueo_detalle> Arqueo_detalle { get; set; }
    }
}
