//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arqueo_detalle
    {
        public int id_arqueo_detalle { get; set; }
        public Nullable<int> id_arqueo { get; set; }
        public Nullable<int> id_denominacion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> estado_registro { get; set; }
        public Nullable<int> tipo_arqueo { get; set; }
    
        public virtual Arqueos Arqueos { get; set; }
        public virtual Denominaciones Denominaciones { get; set; }
    }
}
