//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public Nullable<int> id_empleado_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string clave { get; set; }
        public string concepto { get; set; }
        public string modulo { get; set; }
        public Nullable<bool> registroActivo { get; set; }
    }
}
