//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierraCaja
    {
        public int id_cierre { get; set; }
        public Nullable<decimal> saldo_inicial { get; set; }
        public Nullable<decimal> saldo_final { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_empleado_cierre { get; set; }
        public Nullable<decimal> tipo_cambio { get; set; }
        public Nullable<decimal> saldo_inicial_dolares { get; set; }
        public Nullable<decimal> saldo_final_dolares { get; set; }
    }
}
