//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.DocumentosCuentasCobrar = new HashSet<DocumentosCuentasCobrar>();
            this.Representante_Cliente = new HashSet<Representante_Cliente>();
            this.Prestamos = new HashSet<Prestamos>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string ruc { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public bool activo { get; set; }
        public Nullable<int> id_sector { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<int> id_representante { get; set; }
        public Nullable<int> id_representante_2 { get; set; }
        public Nullable<int> id_representante_3 { get; set; }
        public string repre1 { get; set; }
        public string cedula1 { get; set; }
        public string repre2 { get; set; }
        public string cedula2 { get; set; }
        public string repre3 { get; set; }
        public string cedula3 { get; set; }
        public byte[] imagen_documento { get; set; }
        public string departamento { get; set; }
        public Nullable<bool> esMercado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosCuentasCobrar> DocumentosCuentasCobrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Representante_Cliente> Representante_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
