//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteDiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComprobanteDiario()
        {
            this.ComprasDiario = new HashSet<ComprasDiario>();
            this.ComprobanteDiarioDetalle = new HashSet<ComprobanteDiarioDetalle>();
            this.VentasDiario = new HashSet<VentasDiario>();
        }
    
        public int id { get; set; }
        public Nullable<int> numero_comprobante { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> periodo_ini { get; set; }
        public Nullable<System.DateTime> periodo_fin { get; set; }
        public Nullable<System.DateTime> fecha_asiento { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> tipo_comprobante { get; set; }
        public Nullable<int> id_empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDiario> ComprasDiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprobanteDiarioDetalle> ComprobanteDiarioDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasDiario> VentasDiario { get; set; }
    }
}
