//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasDetalle
    {
        public int id { get; set; }
        public int id_compra { get; set; }
        public int id_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_lote { get; set; }
        public string ubicacion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Compras Compras { get; set; }
    }
}
