//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasDiario
    {
        public int id { get; set; }
        public Nullable<int> id_compra { get; set; }
        public Nullable<int> id_comprobante { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual ComprobanteDiario ComprobanteDiario { get; set; }
    }
}
