//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public int id { get; set; }
        public string numero_cuenta { get; set; }
        public string nombre_cuenta { get; set; }
        public string naturaleza { get; set; }
        public string clasificacion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> agrupacion { get; set; }
        public Nullable<int> deslizamiento { get; set; }
        public Nullable<int> nivel { get; set; }
    }
}
