//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denominaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Denominaciones()
        {
            this.Arqueo_detalle = new HashSet<Arqueo_detalle>();
        }
    
        public int id_denominacion { get; set; }
        public decimal denominacion { get; set; }
        public Nullable<int> tipo_denominacion { get; set; }
        public bool decimales { get; set; }
        public int tipo_moneda { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> orden_aparicion { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arqueo_detalle> Arqueo_detalle { get; set; }
    }
}
