//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Lotes = new HashSet<Lotes>();
            this.Prestamos = new HashSet<Prestamos>();
            this.Venta = new HashSet<Venta>();
            this.EmpleadoHuella = new HashSet<EmpleadoHuella>();
            this.UsuariosRolesPermisos = new HashSet<UsuariosRolesPermisos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string cargo { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string direccion { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
        public byte[] foto { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<int> tipo_empleado { get; set; }
        public string codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lotes> Lotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoHuella> EmpleadoHuella { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosRolesPermisos> UsuariosRolesPermisos { get; set; }
    }
}
