//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormaPago()
        {
            this.FormaPagoVenta = new HashSet<FormaPagoVenta>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string descripcion_corta { get; set; }
        public int moneda { get; set; }
        public Nullable<bool> efectivo { get; set; }
        public byte[] imagen { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormaPagoVenta> FormaPagoVenta { get; set; }
    }
}
