//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public int id_producto { get; set; }
        public int id_bodega { get; set; }
        public string ubicacion { get; set; }
        public decimal saldo_inicial { get; set; }
        public decimal entradas { get; set; }
        public decimal salidas { get; set; }
        public decimal ajuste { get; set; }
        public decimal comprometido { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public int id_kardex { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<decimal> prestamos { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Lotes Lotes { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
