//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Linea()
        {
            this.Precio_detalle_linea = new HashSet<Precio_detalle_linea>();
            this.Producto = new HashSet<Producto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<decimal> precio_mayor { get; set; }
        public Nullable<decimal> precio_eventual { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> precio_4 { get; set; }
        public string codigo { get; set; }
        public Nullable<int> moneda_subgrupo { get; set; }
        public string descripcion_subgrupo { get; set; }
        public Nullable<decimal> precio_5 { get; set; }
        public Nullable<decimal> precio_6 { get; set; }
        public Nullable<decimal> precio_7 { get; set; }
        public Nullable<decimal> precio_8 { get; set; }
        public Nullable<decimal> precio_9 { get; set; }
        public Nullable<decimal> precio_10 { get; set; }
        public Nullable<decimal> precio_11 { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<bool> permiteEdicion { get; set; }
        public Nullable<decimal> precio_12 { get; set; }
        public Nullable<decimal> precio_13 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio_detalle_linea> Precio_detalle_linea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
