//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public long id_login { get; set; }
        public System.DateTime entrada_dia { get; set; }
        public Nullable<System.DateTime> salida_dia { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public bool logueado { get; set; }
        public Nullable<int> duracion { get; set; }
        public string hostname { get; set; }
        public string ip { get; set; }
        public Nullable<System.TimeSpan> fecha_ultima_modificacion { get; set; }
    }
}
