//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientoCaja()
        {
            this.MovimientoCajaDetalle = new HashSet<MovimientoCajaDetalle>();
        }
    
        public int id_movimiento { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string numero_referencia { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_persona { get; set; }
        public string concepto { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> tipo_movimiento { get; set; }
    
        public virtual PersonaReferencia PersonaReferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoCajaDetalle> MovimientoCajaDetalle { get; set; }
    }
}
