//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientoInventario()
        {
            this.MovimientoInventarioDetalle = new HashSet<MovimientoInventarioDetalle>();
        }
    
        public int id { get; set; }
        public int id_tipo_ajuste { get; set; }
        public string numero_documento { get; set; }
        public System.DateTime fecha_documento { get; set; }
        public string numero_referencia { get; set; }
        public string observacion { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public string persona_referencia { get; set; }
        public Nullable<bool> activo { get; set; }
        public bool mes_cerrado { get; set; }
        public int tipo { get; set; }
        public int id_referencia { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoInventarioDetalle> MovimientoInventarioDetalle { get; set; }
    }
}
