//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoInventarioDetalle
    {
        public int id { get; set; }
        public int id_movimiento { get; set; }
        public int id_bodega { get; set; }
        public int id_producto { get; set; }
        public decimal cantidad { get; set; }
        public decimal costo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
        public Nullable<int> id_lote { get; set; }
        public string ubicacion { get; set; }
    
        public virtual MovimientoInventario MovimientoInventario { get; set; }
    }
}
