//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoCajaDetalle
    {
        public int id_movimiento_detalle { get; set; }
        public Nullable<int> id_movimiento { get; set; }
        public Nullable<decimal> tipo_cambio { get; set; }
        public Nullable<decimal> ingreso { get; set; }
        public Nullable<decimal> egreso { get; set; }
        public Nullable<int> id_forma_pago { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> N_Transferencia { get; set; }
        public Nullable<System.DateTime> fecha_deposito { get; set; }
        public string banco { get; set; }
    
        public virtual MovimientoCaja MovimientoCaja { get; set; }
    }
}
