//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosCuentasContables
    {
        public int id_parametro { get; set; }
        public int nivel { get; set; }
        public int digitos { get; set; }
        public Nullable<int> estado { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
