//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio_detalle_linea
    {
        public int id { get; set; }
        public Nullable<int> id_precio { get; set; }
        public Nullable<int> id_linea { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual Linea Linea { get; set; }
    }
}
