//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Precio_detalle_Productos = new HashSet<Precio_detalle_Productos>();
            this.ComprasDetalle = new HashSet<ComprasDetalle>();
            this.DevolucionesDetalle = new HashSet<DevolucionesDetalle>();
            this.DevolucionesProductoDañadoDetalle = new HashSet<DevolucionesProductoDañadoDetalle>();
            this.Kardex = new HashSet<Kardex>();
            this.Prestamos_Detalle = new HashSet<Prestamos_Detalle>();
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
        public int id_marca { get; set; }
        public Nullable<int> id_linea { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public int moneda { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> utilidad { get; set; }
        public decimal precio1 { get; set; }
        public Nullable<decimal> precio2 { get; set; }
        public Nullable<decimal> precio3 { get; set; }
        public Nullable<decimal> precio4 { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> stock { get; set; }
        public Nullable<decimal> stock_minimo { get; set; }
        public byte[] imagen { get; set; }
        public string numero_serie { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> fecha_ultima_venta { get; set; }
        public Nullable<System.DateTime> fecha_ultima_compra { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<bool> tipo_producto { get; set; }
        public Nullable<int> talla { get; set; }
        public Nullable<decimal> precio5 { get; set; }
        public Nullable<decimal> precio6 { get; set; }
        public Nullable<decimal> precio7 { get; set; }
        public Nullable<decimal> precio8 { get; set; }
        public Nullable<int> id_linea_anterior { get; set; }
        public Nullable<decimal> precio9 { get; set; }
        public Nullable<decimal> precio10 { get; set; }
        public Nullable<decimal> precio11 { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<decimal> precio_12 { get; set; }
        public Nullable<decimal> precio_13 { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Linea Linea { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Precio_detalle_Productos> Precio_detalle_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDetalle> ComprasDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionesDetalle> DevolucionesDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionesProductoDañadoDetalle> DevolucionesProductoDañadoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kardex> Kardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos_Detalle> Prestamos_Detalle { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
