//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Representantes()
        {
            this.Representante_Cliente = new HashSet<Representante_Cliente>();
        }
    
        public int id_representante { get; set; }
        public string nombre_rep { get; set; }
        public string correo { get; set; }
        public string celular { get; set; }
        public string celular2 { get; set; }
        public string direccion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string cedula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Representante_Cliente> Representante_Cliente { get; set; }
    }
}
