//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoFavorCliente
    {
        public int id { get; set; }
        public int id_venta { get; set; }
        public int id_cliente { get; set; }
        public int moneda { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_venta_usada { get; set; }
        public Nullable<int> mov_generado { get; set; }
    }
}
