//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Cambio_Compra
    {
        public int id_cambio_compra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
