//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDocumentosCx
    {
        public int id_tipo_documento { get; set; }
        public int numero_documento { get; set; }
        public string nombre_documento { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public int modulo { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
