//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposAjustes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposAjustes()
        {
            this.AjustesModulos = new HashSet<AjustesModulos>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string descripcion_corta { get; set; }
        public int tipo_movimiento { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AjustesModulos> AjustesModulos { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
